sudo: required
services:
  - docker

before_install:
  - docker build -t llouis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true llouis/react-test npm test -- --coverage

after_success:
  - docker build -t llouis/multi-client ./client
  - docker build -t llouis/multi-nginx ./nginx
  - docker build -t llouis/multi-server ./server
  - docker build -t llouis/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push llouis/multi-client
  - docker push llouis/multi-nginx
  - docker push llouis/multi-server
  - docker push llouis/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-2-529788924674"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
